all:
  hosts:
    fw-blue:
      ansible_host: 10.0.17.200
      ansible_user: vyos
      ansible_network_os: vyos
      ansible_connection: network_cli
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      ansible_password: 'vyos'
  vars:
    network: 10.0.5.0/24
    pool_start: 10.0.5.75
    pool_stop: 10.0.5.125
    default_router: 10.0.5.2
    domain: blue.local
    dns_server: 8.8.8.8
    dhcp_name: bluex
    lease_time: 86400
