---
- name: Configure DHCP on fw-blue
  hosts: fw-blue
  gather_facts: false

  tasks:
    - name: Configure DHCP server
      vyos.vyos.vyos_config:
        lines:
          - "set service dhcp-server shared-network-name {{ dhcp_name }} authoritative"
          - "set service dhcp-server shared-network-name {{ dhcp_name }} subnet {{ network }} default-router {{ default_router }}"
          - "set service dhcp-server shared-network-name {{ dhcp_name }} subnet {{ network }} domain-name {{ domain }}"
          - "set service dhcp-server shared-network-name {{ dhcp_name }} subnet {{ network }} lease {{ lease_time }}"
          - "set service dhcp-server shared-network-name {{ dhcp_name }} subnet {{ network }} name-server {{ dns_server }}"
          - "set service dhcp-server shared-network-name {{ dhcp_name }} subnet {{ network }} range {{ dhcp_name }}--POOL start {{ pool_start }}"
          - "set service dhcp-server shared-network-name {{ dhcp_name }} subnet {{ network }} range {{ dhcp_name }}--POOL stop {{ pool_stop }}"
        match: none
        save: true

    - name: Verify DHCP configuration
      vyos.vyos.vyos_command:
        commands:
          - show dhcp server leases
      register: dhcp_verify

    - name: Print DHCP config output
      debug:
        var: dhcp_verify.stdout_lines