[splunk_server]
splunk-server ansible_host=10.0.5.83 ansible_user=champuser ansible_ssh_private_key_file=~/.ssh/id_rsa

[splunk_agents_linux]
blue-agent-01 ansible_host=10.0.5.82 ansible_user=champuser ansible_ssh_private_key_file=~/.ssh/id_rsa


[splunk_agents_windows]
# Uncomment and configure if targeting Windows agents
# win-agent-01 ansible_host=192.168.1.30 ansible_user=Administrator ansible_password=YourPassword ansible_connection=winrm ansible_winrm_transport=ntlm ansible_winrm_server_cert_validation=ignore

[blue_lan:children]
splunk_server
splunk_agents_linux

[all:vars]
ansible_python_interpreter=/usr/bin/python3
